export const data = [
  {
    id: 1,
    image: "https://avatar.vercel.sh/john",
    language: "TR",
    name: "İsmail",
    surname: "dfhfdsad",
    created_at: "2025-01-28 16:30:25.125412",
    body: "weecoins premium kriptovalyutanı almağı mənə dostum tövsiyə etdi, baxdım gördüm çox böyük projelərə",
    contact_type: "INSTAGRAM",
    contact: "cr7",
  },
  {
    id: 2,
    image: "https://avatar.vercel.sh/john",
    language: "AZ",
    name: "Orxan",
    surname: "dfhfdsad",
    created_at: "2025-01-27 14:15:10.523698",
    body: "Weecoins platforması mənə kripto yatırımları üçün çox etibarlı gəldi.",
    contact_type: "TWITTER",
    contact: "@orxan_crypto",
  },
  {
    id: 3,
    image: "https://avatar.vercel.sh/john",
    language: "DE",
    name: "Murat",
    surname: "dfhfdsad",
    created_at: "2025-01-26 12:45:33.987654",
    body: "Weecoins sayəsində kripto dünyasına güvənlə adım atdım!",
    contact_type: "TELEGRAM",
    contact: "murat_crypto",
  },
  {
    id: 4,
    image: "https://avatar.vercel.sh/john",
    language: "GB",
    name: "Alice",
    surname: "dfhfdsad",
    created_at: "2025-01-25 18:20:44.741852",
    body: "I found Weecoins very useful for long-term investments.",
    contact_type: "INSTAGRAM",
    contact: "alice_trader",
  },
  {
    id: 5,
    image: "https://avatar.vercel.sh/john",
    language: "FR",
    name: "Jean",
    surname: "dfhfdsad",
    created_at: "2025-01-24 22:10:30.852963",
    body: "Weecoins m’a aidé à comprendre le marché de la crypto.",
    contact_type: "FACEBOOK",
    contact: "jean_crypto",
  },
  {
    id: 6,
    image: "https://avatar.vercel.sh/john",
    language: "US",
    name: "Michael",
    surname: "dfhfdsad",
    created_at: "2025-01-23 11:55:12.365478",
    body: "Weecoins has a solid user experience and great investment options.",
    contact_type: "LINKEDIN",
    contact: "michael_investor",
  },
  {
    id: 7,
    image: "https://avatar.vercel.sh/john",
    language: "IT",
    name: "Giovanni",
    surname: "dfhfdsad",
    created_at: "2025-01-22 17:40:05.123456",
    body: "Investire in Weecoins è stata un'ottima scelta!",
    contact_type: "INSTAGRAM",
    contact: "giovanni_italy",
  },
  {
    id: 8,
    image: "https://avatar.vercel.sh/john",
    language: "ES",
    name: "Carlos",
    surname: "dfhfdsad",
    created_at: "2025-01-21 13:25:50.654789",
    body: "Weecoins me ayudó a diversificar mis inversiones.",
    contact_type: "WHATSAPP",
    contact: "+34678901234",
  },
  {
    id: 9,
    image: "https://avatar.vercel.sh/john",
    language: "RU",
    name: "Dmitry",
    surname: "dfhfdsad",
    created_at: "2025-01-20 10:10:15.789654",
    body: "Weecoins — надежный выбор для криптоинвестиций.",
    contact_type: "TELEGRAM",
    contact: "dmitry_crypto",
  },
  {
    id: 10,
    image: "https://avatar.vercel.sh/john",
    language: "CN",
    name: "Li Wei",
    surname: "dfhfdsad",
    created_at: "2025-01-19 15:55:05.234567",
    body: "Weecoins是我进入加密市场的第一步！",
    contact_type: "WECHAT",
    contact: "liwei_crypto",
  },
  {
    id: 11,
    image: "https://avatar.vercel.sh/john",
    language: "IN",
    name: "Arjun",
    surname: "dfhfdsad",
    created_at: "2025-01-18 20:45:30.987123",
    body: "Weecoins has given me great insights into crypto trading.",
    contact_type: "TWITTER",
    contact: "@arjun_crypto",
  },
  {
    id: 12,
    image: "https://avatar.vercel.sh/john",
    language: "BR",
    name: "Lucas",
    surname: "dfhfdsad",
    created_at: "2025-01-17 09:30:25.874512",
    body: "Weecoins é uma plataforma incrível para novos investidores!",
    contact_type: "INSTAGRAM",
    contact: "lucas_trader",
  },
  {
    id: 13,
    image: "https://avatar.vercel.sh/john",
    language: "TR",
    name: "Mehmet",
    surname: "dfhfdsad",
    created_at: "2025-01-16 16:05:45.365214",
    body: "Weecoins ile kripto yatırımlarıma güvenle devam ediyorum.",
    contact_type: "FACEBOOK",
    contact: "mehmet_crypto",
  },
  {
    id: 14,
    image: "https://avatar.vercel.sh/john",
    language: "JP",
    name: "Hiroshi",
    surname: "dfhfdsad",
    created_at: "2025-01-15 12:20:55.741852",
    body: "Weecoinsは投資のための素晴らしいプラットフォームです。",
    contact_type: "TWITTER",
    contact: "@hiroshi_crypto",
  },
  {
    id: 15,
    image: "https://avatar.vercel.sh/john",
    language: "KR",
    name: "Jisoo",
    surname: "dfhfdsad",
    created_at: "2025-01-14T19:35:40.963852",
    body: "Weecoins 덕분에 암호화폐 투자에 대한 자신감을 얻었습니다.",
    contact_type: "INSTAGRAM",
    contact: "jisoo_crypto",
  },
  {
    id: 16,
    image: "https://avatar.vercel.sh/john",
    language: "SA",
    name: "Omar",
    surname: "dfhfdsad",
    created_at: "2025-01-13T08:50:20.258963",
    body: "Weecoins ساعدني في فهم أساسيات الاستثمار في العملات الرقمية.",
    contact_type: "WHATSAPP",
    contact: "+966555123456",
  },
];
